version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - json-server

  json-server:
    build:
      context: .
      dockerfile: Dockerfile.json-server
    ports:
      - "3000:3000"